backend:
  name: github
  repo: Archangel-code/thesolarityproject
  branch: main
  auth_scope: repo
  base_url: https://thesolarityproject.netlify.app
  auth_endpoint: api/auth

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "chapters"
    label: "Chapters"
    folder: "chapters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
